### ISSUE TITLE
ConsensusGatewayBase contract creation

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#117]
- This will be the base contract for `ConsensusGateway` and `ConsensusCogateway` contracts
- The `ConsensusGatewayBase` contract will inherit from `ConsensusModule` contract
  - `ConsensusGatewayBase is ConsensusModule`
- It should store the following variables:
  - ERC20Token instance variable for `MOST` and `utMOST` in `ConsensusGateway` and `ConsensusCogateway` contracts respectively 
    - `ERC20I public most;`
  - A Mapping to store the nonce of senders. This will track the nonce that will be used in message declaration and confirmation
    - `mapping(address => uint256) nonces;`
  - A `uint256` variable to store the current metablock height. This will be used to compare with the height returned from `core.getOpenKernel` to track of the latest height of the latest open metablock
    - `uint256 currentMetablockHeight;`

**Comment by 0xsarvesh** [comment]
As mentioned `ConsensusGatewayBase` will be used for both `ConsensusGateway` and `ConsensusCogateway`.  Also, `ConsensusGatewayBase` is `ConsensusModule`. 

But in the current implementation, `ConsensusModule` has `ConsensusI` which has methods for origin consensus contract. 

The proposal is to changes the consensus module to use `address` instead of `ConsensusI`.

**Comment by 0xsarvesh** [comment]
Discussion notes: 

Instead of a single type `ConsensusModule`, there should exit separate types `CoConsensusModule` for the auxiliary chain. 

ConsensusGateaway should include ConsensusModule and CoConsensusGateway should include CoConsensusModule.
