### ISSUE TITLE
Implement Protocore::upsert()

### ISSUE THREAD

**Issue by jayeshbairagi** [OpenST/compute#179]
1. Implement `Protocore::upsert()` external function
    - Checks the reputation of the validator
    - We check 
        - if the validator is already there and has a +ve reputation, then no change
        - if the validator is not there and has a +ve reputation, then it is joining in the next metablock height
        - if the validator's reputation is zero, then it is logging out
        - (and other cases)
    - Proposal
    ```solidity
    function upsert(
        address _validator,
        uint256 _height,
        uint256 _reputation
    )
        external
    ```

**Comment by gulshanvasnani** [comment]
@jayeshbairagi , There is not maintenance of validator reputation in Protocore.
So,  do you mean `Protocore::upsert` will update **validatorBeginHeight** and **validatorEndHeight** ?

**Comment by jayeshbairagi** [comment]
Yes, it will update the `validatorBeginHeight` and `validatorEndHeight` and the reputation will not be updated in Protocore

**Comment by deepesh-kn** [comment]
There are 2 points that want to update here.
1. In the PR I asked to update the following functions to include `uint256 _openKernelHeight` param. This will help to check the conditions related to `openKernelHeight`. Otherwise, these checks has to be done at the places from where it will be called. I think that it will be from `Core` and `SelfProtocore` contracts. 
```
    function insertValidatorInternal(
        address _validator,
        uint256 _beginHeight,
        uint256 _openKernelHeight
    )	   
        internal
```
and
```
    function removeValidatorInternal(
        address _validator,
        uint256 _endHeight,
        uint256 _openKernelHeight
    )
       internal
```
2. Similarly, for `upsert` function, do you think that there should be an explicit check for validator end height should be `MAX_FUTURE_END_HEIGHT` in addition to that it exists in validator set in order to call `removeValidatorInternal`? 
The upsert function should not revert, so this check will be a safegaurd.
```
if(validators[_validator] != address(0)) {
            if(_reputation == 0) {
                removeValidatorInternal(_validator, _height, openKernelHeight);
            }
        }
        else {
            if(_reputation > 0) {
                insertValidatorInternal(_validator, _height, openKernelHeight);
            }
        }
```
Please let me know what do you think? cc: @benjaminbollen , @pgev 
Please see this PR for details https://github.com/mosaicdao/mosaic-1/pull/230

**Comment by benjaminbollen** [comment]
on 1. we don't need to change the interface of `ValidatorSet`; rather in `SelfProtocore::upsert` we can add `assert(_height == openKernelHeight.add(1))`.  This forces the choice that we first from coconsensus upsert all validators, then call `Protocore::openMetablock`

on 2. 

```
assert(_height == openKernelHeight.add(1));
if (inValidatorSet(_validator, _height)) {
  if(_reputation == 0) {
    removeValidatorInternal(_validator, _height);
  }
} else {
  if(_reputation > 0) {
    insertValidatorInternal(_validator, _height);
  }
}
```
